package Frames.mono;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import org.jdesktop.beansbinding.*;

public class PrimaPagina extends javax.swing.JFrame {

    /**
     * Creates new form PrimaPagina
     */
    public PrimaPagina() {
        initComponents();
        PasswField.requestFocusInWindow();
        impostaDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPasswordField1 = new javax.swing.JPasswordField();
        ConnettiB = new javax.swing.JButton();
        ServiceLabel = new javax.swing.JLabel();
        SchemaLabel = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        PasswLabel = new javax.swing.JLabel();
        ServiceField = new javax.swing.JTextField();
        SchemaField = new javax.swing.JTextField();
        UserField = new javax.swing.JTextField();
        PortLabel = new javax.swing.JLabel();
        HostLabel = new javax.swing.JLabel();
        PortField = new javax.swing.JTextField();
        HostField = new javax.swing.JTextField();
        TitleLabel = new javax.swing.JLabel();
        AnnullaB = new javax.swing.JButton();
        CheckBox = new javax.swing.JCheckBox();
        PasswField = new javax.swing.JPasswordField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log");
        setResizable(false);

        ConnettiB.setText("Connetti");
        ConnettiB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnettiBActionPerformed(evt);
            }
        });

        ServiceLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        ServiceLabel.setText("Servizio:");

        SchemaLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        SchemaLabel.setText("Schema:");

        UserLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        UserLabel.setText("Utente:");

        PasswLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        PasswLabel.setText("Password:");

        ServiceField.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        ServiceField.setText("XE");

        SchemaField.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, UserField, org.jdesktop.beansbinding.ELProperty.create("${text}"), SchemaField, org.jdesktop.beansbinding.BeanProperty.create("text"), "bindSchema");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, CheckBox, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), SchemaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        UserField.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        UserField.setText("Utente");
        UserField.setDragEnabled(true);
        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });

        PortLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        PortLabel.setText("Porta:");

        HostLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        HostLabel.setText("Host:");

        PortField.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        PortField.setText("1521");
        PortField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortFieldActionPerformed(evt);
            }
        });

        HostField.setFont(new java.awt.Font("Calibri", 2, 13)); // NOI18N
        HostField.setText("localhost");

        TitleLabel.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        TitleLabel.setText("Login");

        AnnullaB.setText("Annulla");
        AnnullaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnullaBActionPerformed(evt);
            }
        });

        CheckBox.setFont(new java.awt.Font("Cambria Math", 2, 10)); // NOI18N
        CheckBox.setSelected(true);
        CheckBox.setText("=Utente");
        CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBind(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(AnnullaB)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConnettiB)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PasswLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PasswField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SchemaLabel)
                            .addComponent(ServiceLabel)
                            .addComponent(UserLabel)
                            .addComponent(PortLabel)
                            .addComponent(HostLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(HostField, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(SchemaField)
                            .addComponent(UserField)
                            .addComponent(ServiceField)
                            .addComponent(PortField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HostLabel)
                    .addComponent(HostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PortLabel)
                    .addComponent(PortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServiceLabel)
                    .addComponent(ServiceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SchemaLabel)
                    .addComponent(SchemaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserLabel)
                    .addComponent(PasswLabel)
                    .addComponent(UserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConnettiB)
                    .addComponent(AnnullaB))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConnettiBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnettiBActionPerformed
        DBConnect.host=HostField.getText();
        try{
            DBConnect.porta=Integer.parseInt(PortField.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"La porta deve necessariamente essere un numero","Errore", JOptionPane.ERROR_MESSAGE);
        }
        DBConnect.schema=SchemaField.getText();
        DBConnect.servizio=ServiceField.getText();
        DBConnect.user=UserField.getText();
        DBConnect.password= PasswField.getText();
        try{
            DBConnect.setDefaultConnection(DBConnect.nuovaConnessione());
            JOptionPane.showMessageDialog(this, "Sei connesso...");
            setVisible(false);
            //this.dispose();  //da controllare
            SecondaPagina seconda= new SecondaPagina();
            seconda.setVisible(true);

        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Connessione fallita(Credenziali errate ?)", "Errore", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_ConnettiBActionPerformed

    private void impostaDefault() {
      getRootPane().setDefaultButton(ConnettiB);
   }
    
    private void PortFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PortFieldActionPerformed

    private void AnnullaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnullaBActionPerformed
        dispose();
    }//GEN-LAST:event_AnnullaBActionPerformed

    
    private void CheckBind(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBind
        Binding bind= bindingGroup.getBinding("bindSchema");
        if(bind.isBound()){
            bind.unbind();
        }else{
            bind.bind();
        }
    }//GEN-LAST:event_CheckBind

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimaPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimaPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimaPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimaPagina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimaPagina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnullaB;
    private javax.swing.JCheckBox CheckBox;
    private javax.swing.JButton ConnettiB;
    private javax.swing.JTextField HostField;
    private javax.swing.JLabel HostLabel;
    private javax.swing.JPasswordField PasswField;
    private javax.swing.JLabel PasswLabel;
    private javax.swing.JTextField PortField;
    private javax.swing.JLabel PortLabel;
    private javax.swing.JTextField SchemaField;
    private javax.swing.JLabel SchemaLabel;
    private javax.swing.JTextField ServiceField;
    private javax.swing.JLabel ServiceLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JTextField UserField;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JPasswordField jPasswordField1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
