package Panels.mono;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author marco
 */
public class InfoCarte extends javax.swing.JPanel {
    Connection myconObj;
    static int IDPartita;
    /**
     * Creates new form InfoCarte
     */
    public InfoCarte() {
        initComponents();
        selectionall();
    }
    public static void setid(int m){
        IDPartita=m;
        
    }
    public void selectionall(){
        DefaultTableModel model=(DefaultTableModel)TableCarte.getModel();
        model.setRowCount(0);
        TableColumnModel columnModel= TableCarte.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(8);
        columnModel.getColumn(1).setPreferredWidth(500);
        columnModel.getColumn(2).setPreferredWidth(60);
        try{
            myconObj=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Utente","12345");
            Statement mystat1Obj = myconObj.createStatement();
            Statement mystat2Obj = myconObj.createStatement();
            ResultSet partita=mystat2Obj.executeQuery("SELECT Max(IDPartita) as idp FROM Partita");
            partita.next();
            System.out.println(partita.getInt("idp"));
            ResultSet carte=mystat1Obj.executeQuery("SELECT NumeroCarta, Descrizione,ImpOProb FROM carta WHERE IDPartita="+partita.getInt("idp")+ "ORDER BY NumeroCarta,ImpOProb");
            while(carte.next()){
                model.addRow(new Object[]{carte.getInt("NumeroCarta"),carte.getString("Descrizione"),carte.getString("ImpOProb")});
            }
            System.out.println("chiudo connessione");
            myconObj.close();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableCarte = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        TableCarte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Descrizione", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableCarte);
        if (TableCarte.getColumnModel().getColumnCount() > 0) {
            TableCarte.getColumnModel().getColumn(0).setResizable(false);
            TableCarte.getColumnModel().getColumn(1).setResizable(false);
            TableCarte.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("CARTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCarte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
