/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogs.mono;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author marco
 */
public class InfoStoredLogs extends javax.swing.JDialog {
    Connection myconObj;
    int IDPartita;
    /**
     * Creates new form InfoStoredLogs
     */
    public InfoStoredLogs(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Jova.setText("I log dei partecipanti della partita numero "+IDPartita);
    }
    public void setid(int m){
        IDPartita=m;
        selectionall();
    }
   public void selectionall(){
        DefaultTableModel model=(DefaultTableModel)TableLogs.getModel();
        model.setRowCount(0);
        try{
        myconObj=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Utente","12345");
        Statement mystat1Obj = myconObj.createStatement();
        Statement mystat2Obj= myconObj.createStatement();
        Statement mystat3Obj= myconObj.createStatement();
        
        ResultSet lastlog = mystat3Obj.executeQuery( "select partecipante.pedina as Pedina,logpartecipante.turno as Turno,logpartecipante.posizione as Posizione,logpartecipante.saldo as Saldo,logpartecipante.inprigione as Prigioniero,partecipante.eliminato as Eliminato, logpartecipante.numcontratti as ncon,logpartecipante.ordine as ord FROM logpartecipante, partecipante where partecipante.idpartita=logpartecipante.idpartita and logpartecipante.idpartita="+IDPartita+" and logpartecipante.pedina=partecipante.pedina ORDER BY LogPartecipante.Turno");            

        while(lastlog.next()){
            model.addRow(new Object[]{lastlog.getString("Pedina"),lastlog.getString("Turno"),lastlog.getInt("ord"),lastlog.getInt("Saldo"),lastlog.getInt("ncon"),lastlog.getInt("Posizione"),lastlog.getInt("prigioniero"),lastlog.getInt("eliminato")});
        }
        myconObj.close();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jova = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableLogs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LogPartecipanti");

        TableLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pedina", "Turno", "Ordine", "Saldo", "Num. contratti", "Posizione", "Prigioniero", "Eliminato"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableLogs);
        if (TableLogs.getColumnModel().getColumnCount() > 0) {
            TableLogs.getColumnModel().getColumn(0).setResizable(false);
            TableLogs.getColumnModel().getColumn(1).setResizable(false);
            TableLogs.getColumnModel().getColumn(2).setResizable(false);
            TableLogs.getColumnModel().getColumn(3).setResizable(false);
            TableLogs.getColumnModel().getColumn(4).setResizable(false);
            TableLogs.getColumnModel().getColumn(5).setResizable(false);
            TableLogs.getColumnModel().getColumn(6).setResizable(false);
            TableLogs.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jova, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jova, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoStoredLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoStoredLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoStoredLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoStoredLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InfoStoredLogs dialog = new InfoStoredLogs(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jova;
    private javax.swing.JTable TableLogs;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
