package Dialogs.mono;

import java.sql.*;
import javax.swing.JOptionPane;


public class InizializzaPartita extends javax.swing.JDialog {
    String Partecipante;
    int IDPartita,NumContratto;
    Connection myconObj=null;
    public int Premuto=0;
    /**
     * Creates new form InizializzaPartita
     */
    public InizializzaPartita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(AssegnaButton);
        ContrattoField.requestFocusInWindow();
    }
    public void setNum(int i){
        NumContratto=i;
    }
    public void setIDPartita(int i){
        IDPartita=i;
    }
    public void setPartecipante(String i){
        Partecipante=i;
        MessaggioArea.setText("Inserire il contratto "+NumContratto+" della pedina "+Partecipante+":");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        MessaggioArea = new javax.swing.JTextArea();
        MainLabel = new javax.swing.JLabel();
        ContrattoField = new javax.swing.JTextField();
        AssegnaButton = new javax.swing.JButton();
        AnnulButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MessaggioArea.setEditable(false);
        MessaggioArea.setColumns(20);
        MessaggioArea.setRows(2);
        jScrollPane1.setViewportView(MessaggioArea);

        MainLabel.setText("Nome contratto:");

        AssegnaButton.setText("Assegna");
        AssegnaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssegnaButtonActionPerformed(evt);
            }
        });

        AnnulButton.setText("Annulla");
        AnnulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainLabel)
                .addGap(18, 18, 18)
                .addComponent(ContrattoField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(AssegnaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(AnnulButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContrattoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AssegnaButton)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AnnulButton)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Gli assegnamenti fatti andranno persi.");
        Premuto=1;
        this.dispose();
    }//GEN-LAST:event_AnnulButtonActionPerformed

    private void AssegnaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssegnaButtonActionPerformed
        if(!ContrattoField.getText().trim().isEmpty()){
            try{
                myconObj=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "Utente","12345");
                
                //controllo che il contratto esiste
                Statement cop=myconObj.createStatement();
                ResultSet contrp=cop.executeQuery("Select Nome FROM Contratti WHERE Nome='"+ContrattoField.getText()+"'");
                if(contrp.next()){
                    //Controllo che il contratto scelto non appartenga a nessuno 
                    Statement co=myconObj.createStatement();
                    ResultSet contr=co.executeQuery("SELECT Pedina FROM Contratti WHERE IDPartita="+IDPartita+"and Nome='"+ContrattoField.getText()+"'");
                    if(!contr.next()){
                        JOptionPane.showMessageDialog(this, "Assegnare un contratto a"+Partecipante+" che non appartiene già a qualcuno");
                    }else{
                        Statement tot=myconObj.createStatement();
                        tot.executeUpdate("INSERT INTO MOSSA VALUES (0,0,0,0,0,1,null,'"+Partecipante+"',"+IDPartita+",null,null,null,'"+ContrattoField.getText()+"',null,"+IDPartita+","+IDPartita+",null,"+(NumContratto-1)+")");
                        this.dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Il contratto non esiste");
                }
            }
            catch(SQLException e){e.printStackTrace();}
        }else{
            JOptionPane.showMessageDialog(this, "Assegnare un contratto a"+Partecipante);
        }
    }//GEN-LAST:event_AssegnaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InizializzaPartita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InizializzaPartita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InizializzaPartita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InizializzaPartita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InizializzaPartita dialog = new InizializzaPartita(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulButton;
    private javax.swing.JButton AssegnaButton;
    private javax.swing.JTextField ContrattoField;
    private javax.swing.JLabel MainLabel;
    private javax.swing.JTextArea MessaggioArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
